language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
global:
 - export NODE_ENV=test
addons:
    postgresql: "9.6"
services:
  - postgresql
before_script:
  - psql -c "create user gerrard with password 'testdb';" -U postgres
  - psql -c 'create database epic-mail;' -U postgres
  - npm install
script: 
  - npm run test
after_success:
  - npm run coverage
  - npm run report-coverage
  - npm run coveralls